# Generated by Django 4.0.5 on 2022-06-04 16:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator])),
                ('number', models.CharField(max_length=15, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=25, unique=True)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('bep-2', 'BEP-2'), ('bep-20', 'BEP-20'), ('trc-20', 'TRC-20'), ('erc-20', 'ERC-20')], max_length=10)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.baseuser')),
                ('wallet', models.ManyToManyField(related_name='trader', to='account.wallet')),
            ],
            bases=('account.baseuser',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.baseuser')),
                ('user_trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='army', to='account.trader')),
            ],
            bases=('account.baseuser',),
        ),
    ]
