# Generated by Django 4.0.5 on 2022-06-04 20:14

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_historicaltrader_historicaluser_remove_trader_wallet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('order_type', models.CharField(choices=[('limit', 'LIMIT'), ('market', 'MARKET')], max_length=8)),
                ('type', models.CharField(choices=[('long', 'LONG'), ('short', 'SHORT')], max_length=8)),
                ('entry', models.FloatField(max_length=20)),
                ('targets', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=20), size=None)),
                ('stop_loss', models.FloatField(max_length=20)),
                ('capital', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('risk', models.CharField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH')], default='medium', max_length=8)),
                ('risk_reward', models.FloatField(blank=True)),
                ('leverage', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('timeframe', models.CharField(choices=[('1m', '1M'), ('5m', '5M'), ('15m', '15M'), ('30m', '30M'), ('45m', '45M'), ('1h', '1H'), ('2h', '2H'), ('3h', '3H'), ('4h', '4H'), ('8h', '8H'), ('1d', '1D'), ('1w', '1W'), ('1mo', '1MO')], max_length=8)),
                ('status', models.CharField(choices=[('not_filled', 'NOT_FILLED'), ('filled', 'FILLED'), ('targeted', 'TARGETED'), ('stopped', 'STOPPED')], max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='account.trader')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net', models.FloatField(blank=True, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='market.signal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTrade',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('net', models.FloatField(blank=True, max_length=20)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='market.signal')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.user')),
            ],
            options={
                'verbose_name': 'historical trade',
                'verbose_name_plural': 'historical trades',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSignal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('order_type', models.CharField(choices=[('limit', 'LIMIT'), ('market', 'MARKET')], max_length=8)),
                ('type', models.CharField(choices=[('long', 'LONG'), ('short', 'SHORT')], max_length=8)),
                ('entry', models.FloatField(max_length=20)),
                ('targets', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=20), size=None)),
                ('stop_loss', models.FloatField(max_length=20)),
                ('capital', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('risk', models.CharField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH')], default='medium', max_length=8)),
                ('risk_reward', models.FloatField(blank=True)),
                ('leverage', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('timeframe', models.CharField(choices=[('1m', '1M'), ('5m', '5M'), ('15m', '15M'), ('30m', '30M'), ('45m', '45M'), ('1h', '1H'), ('2h', '2H'), ('3h', '3H'), ('4h', '4H'), ('8h', '8H'), ('1d', '1D'), ('1w', '1W'), ('1mo', '1MO')], max_length=8)),
                ('status', models.CharField(choices=[('not_filled', 'NOT_FILLED'), ('filled', 'FILLED'), ('targeted', 'TARGETED'), ('stopped', 'STOPPED')], max_length=12)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trader', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.trader')),
            ],
            options={
                'verbose_name': 'historical signal',
                'verbose_name_plural': 'historical signals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
