# Generated by Django 4.0.5 on 2022-06-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsignal',
            name='status',
            field=models.CharField(choices=[('not_filled', 'NOT_FILLED'), ('filled', 'FILLED'), ('targeted', 'TARGETED'), ('stopped', 'STOPPED')], default='not_filled', max_length=12),
        ),
        migrations.AlterField(
            model_name='signal',
            name='status',
            field=models.CharField(choices=[('not_filled', 'NOT_FILLED'), ('filled', 'FILLED'), ('targeted', 'TARGETED'), ('stopped', 'STOPPED')], default='not_filled', max_length=12),
        ),
    ]
