# Generated by Django 4.0.5 on 2022-06-07 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_historicaluser_cap_user_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('blind_date', 'BLIND_DATE'), ('menu', 'MENU'), ('initiate_wallet', 'INITIATE_WALLET'), ('initiate_exchange', 'INITIATE_EXCHANGE')], max_length=30)),
                ('created', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='account.baseuser')),
            ],
        ),
    ]
